//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class HouseManager
{
	private static HouseManager _Instance = new HouseManager();


	public ShopSystem BuildSystem;
	public ShopSystem ProductSystem;
	public ShopSystem ShopSystem;

	public HouseManager ()
	{

	}

	public static HouseManager Instance{
		get{
			if(_Instance == null)
				_Instance = new HouseManager();
			return _Instance;
		}
	}

	public void Init(){
		BuildSystem = new ShopSystem();
		BuildSystem.Init(Main.BuildingDataPath);

		ProductSystem = new ShopSystem();
		ProductSystem.Init(Main.IndustryDataPath);

		ShopSystem = new ShopSystem();
		ShopSystem.Init(Main.ShopDataPath);
	}

	public void Active(){

	}
}
